### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by dimalinux** [microsoft/Azure-DCAP-Client#128]
Now that Intel's SGX installers officially support Ubuntu 20.04, can Microsoft do the same for the AZ DCAP client?

There is no 20.04 debian package up on `deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main` for the az-dcap client.  I thought I'd try building it myself from source, but the code doesn't compile with g++ 9.3.0 that comes with Ubuntu 20.04.

Thanks!

**Comment by deschuma** [comment]
I will check with the rest of the team and someone will get back to you on publishing a package for Ubuntu 20.04

What was the compilation issue you were setting?

**Comment by dimalinux** [comment]
Errors are below.  The first 2 can just be changed to const references, but the last error looked like something the author should give thought to on how to fix.
```
g++ -fPIC -std=c++14 -Wall -I /usr/local/include/gtest/ -Werror -I/usr/include/x86_64-linux-gnu/curl -I. -I.. -Iext/intel -D__LINUX__ -Wno-unknown-pragmas -pthread -c ../dcap_provider.cpp -o ../dcap_provider.o
../dcap_provider.cpp: In function ‘bool get_cache_expiration_time(const string&, const string&, time_t&)’:
../dcap_provider.cpp:231:38: error: catching polymorphic type ‘class std::invalid_argument’ by value [-Werror=catch-value=]
  231 |         catch (std::invalid_argument e)
      |                                      ^
../dcap_provider.cpp:239:34: error: catching polymorphic type ‘class std::out_of_range’ by value [-Werror=catch-value=]
  239 |         catch (std::out_of_range e)
      |                                  ^
../dcap_provider.cpp: In instantiation of ‘void safe_cast(input_t, output_t*) [with input_t = long unsigned int; output_t = int]’:
../dcap_provider.cpp:677:40:   required from here
../dcap_provider.cpp:447:12: error: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Werror=sign-compare]
  447 |     if (in > (std::numeric_limits<output_t>::max)())
      |         ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
I was able to do `apt-get download az-dcap-client` on a 18.04 host, move the `az-dcap-client_1.6_amd64.deb` file over to the 20.04 host, and then install it there, but life would be easier if the debian file was available in Microsoft's 20.04 apt repo.

**Comment by dimalinux** [comment]
The 20.04 APT packages were provided at some point.
